import logging
import os

BASE_DIR = '/app'

BACKEND = 'Hipchat'

bot_token = os.getenv('bot_token')
bot_id = os.getenv('bot_id')
bot_pswd = os.getenv('bot_pswd')
bot_nick = os.getenv('bot_nick')
bot_endpoint = os.getenv('bot_endpoint')
bot_admins =  os.getenv('bot_admins')
bot_presence =  os.getenv('bot_presence')


BOT_IDENTITY = {
    'username' : bot_id,
    'password' : bot_pswd,
    'token' : bot_token,
    'endpoint': bot_endpoint,
}

CHATROOM_FN = bot_nick

CHATROOM_PRESENCE = (bot_presence,)

# The location where all of Err's data should be stored. Make sure to set
# this to a directory that is writable by the user running the bot.
BOT_DATA_DIR = '/tmp/data'
os.mkdir(BOT_DATA_DIR)

### Repos and plugins config.

# Set this to change from where errbot gets its installable plugin list.
# By default it gets the index from errbot.io which is a file generated by tools/plugin-gen.py.
# BOT_PLUGIN_INDEXES = 'http://version.errbot.io/repos.json'
#
# You can also specify a local file:
# BOT_PLUGIN_INDEXES = 'tools/repos.json'
#
# Or a list. note: if some plugins exists in 2 lists, only the first hit will be taken into account.
# BOT_PLUGIN_INDEXES = ('/data/repos.json', 'https://my.private.tld/errbot/myrepos.json')

# Set this to a directory on your system where you want to load extra
# plugins from, which is useful mostly if you want to develop a plugin
# locally before publishing it. Note that you can specify only a single
# directory, however you are free to create subdirectories with multiple
# plugins inside this directory.
BOT_EXTRA_PLUGIN_DIR = BASE_DIR + "/plugins"
print(BOT_EXTRA_PLUGIN_DIR)

# The location of the log file. If you set this to None, then logging will
# happen to console only.
BOT_LOG_FILE = BOT_DATA_DIR + '/err.log'
BOT_LOG_LEVEL = logging.DEBUG
BOT_LOG_SENTRY = False
SENTRY_DSN = ''
SENTRY_LOGLEVEL = BOT_LOG_LEVEL
BOT_ASYNC = True

# The verbosity level of logging that is done to the above logfile, and to
# the console. This takes the standard Python logging levels, DEBUG, INFO,
# WARN, ERROR. For more info, see http://docs.python.org/library/logging.html
#
# If you encounter any issues with Err, please set your log level to
# logging.DEBUG and attach a log with your bug report to aid the developers
# in debugging the issue.


##########################################################################
# Account and chatroom (MUC) configuration                               #
##########################################################################


# Set the admins of your bot. Only these users will have access
# to the admin-only commands.
#
# Unix-style glob patterns are supported, so 'gbin@localhost'
# would be considered an admin if setting '*@localhost'.
BOT_ADMINS = (bot_admins,)
BOT_ADMINS_NOTIFICATIONS = (bot_admins,)

BOT_ALT_PREFIXES = ('yanbot', '@wwys','@maggot','@errbot',)

PLUGINS_CALLBACK_ORDER = (None, )
XMPP_CA_CERT_FILE = None


